# Generated by Django 6.0.3 on 2026-03-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('template_type', models.CharField(choices=[('admin_booking', 'Admin booking notification'), ('customer_confirmation', 'Customer confirmation')], max_length=32, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Supported placeholders: customer_name, booking_reference, services, total_price, start_at')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LK Nails & Lashes', max_length=120)),
                ('domain', models.CharField(default='lknailslashes.de', max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('map_embed_url', models.URLField(blank=True)),
                ('booking_slot_minutes', models.PositiveIntegerField(default=15)),
                ('concurrent_capacity', models.PositiveIntegerField(default=3)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=64)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
    ]
