# Generated by Django 6.0.3 on 2026-03-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
