# Generated by Django 6.0.3 on 2026-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_smtp_app_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_sender_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
