# Generated by Django 4.2.7 on 2025-09-04 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(default=datetime.time(9, 0))),
                ('closing_time', models.TimeField(default=datetime.time(18, 0))),
                ('break_start', models.TimeField(blank=True, help_text='Mittagspause Start', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Mittagspause Ende', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Öffnungszeit',
                'verbose_name_plural': 'Öffnungszeiten',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Konfiguration', max_length=100)),
                ('smtp_server', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.EmailField(max_length=254)),
                ('smtp_password', models.CharField(help_text='App-Passwort für Gmail', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('admin_email', models.EmailField(help_text='E-Mail für Admin-Benachrichtigungen', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail Konfiguration',
                'verbose_name_plural': 'E-Mail Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(help_text='SEO Titel für die Seite', max_length=200)),
                ('meta_description', models.TextField(help_text='Meta Description für Suchmaschinen', max_length=160)),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta Keywords (komma-getrennt)')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph Titel', max_length=100)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph Description', max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph Bild', null=True, upload_to='seo/')),
                ('structured_data', models.JSONField(blank=True, help_text='JSON-LD Structured Data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Einstellung',
                'verbose_name_plural': 'SEO Einstellungen',
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_duration',
            field=models.PositiveIntegerField(default=0, help_text='Gesamtdauer in Minuten'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta Description für Suchmaschinen', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='SEO Keywords (komma-getrennt)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Titel (falls leer, wird Titel verwendet)', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph Description', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph Titel', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta Description für Suchmaschinen', max_length=160),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='SEO Keywords (komma-getrennt)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Titel (falls leer, wird Name verwendet)', max_length=200),
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='Preis zum Zeitpunkt der Buchung', max_digits=8)),
                ('duration_at_booking', models.PositiveIntegerField(help_text='Dauer in Minuten zum Zeitpunkt der Buchung')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='salon.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service')),
            ],
            options={
                'verbose_name': 'Termin Service',
                'verbose_name_plural': 'Termin Services',
                'unique_together': {('appointment', 'service')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(help_text='Gebuchte Services', through='salon.AppointmentService', to='salon.service'),
        ),
    ]
