# Generated by Django 5.2.6 on 2025-09-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_review_options_review_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='E-Mail-Adresse des Empfängers', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Name des Empfängers', max_length=200)),
                ('sender_email', models.EmailField(help_text='E-Mail-Adresse des Absenders', max_length=254)),
                ('subject', models.CharField(help_text='E-Mail Betreff', max_length=255)),
                ('email_type', models.CharField(choices=[('appointment_confirmation', 'Terminbestätigung'), ('appointment_cancellation', 'Terminabsage'), ('appointment_reminder', 'Terminerinnerung'), ('newsletter', 'Newsletter'), ('promotional', 'Werbung'), ('admin_notification', 'Admin Benachrichtigung'), ('other', 'Sonstiges')], help_text='Art der E-Mail', max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen'), ('pending', 'Ausstehend')], default='pending', help_text='Status der E-Mail', max_length=20)),
                ('message_preview', models.TextField(blank=True, help_text='Vorschau der Nachricht (erste 500 Zeichen)', max_length=500)),
                ('full_message', models.TextField(blank=True, help_text='Vollständige Nachricht')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Zeitpunkt des Versands', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Fehlermeldung falls Versand fehlgeschlagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Zugehöriger Termin', null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.appointment')),
                ('customer', models.ForeignKey(blank=True, help_text='Zugehöriger Kunde', null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.customer')),
            ],
            options={
                'verbose_name': 'E-Mail Log',
                'verbose_name_plural': 'E-Mail Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
