# Generated by Django 5.2.6 on 2025-09-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name des Templates', max_length=200)),
                ('email_type', models.CharField(choices=[('appointment_confirmation', 'Terminbestätigung'), ('appointment_cancellation', 'Terminabsage'), ('appointment_reminder', 'Terminerinnerung'), ('welcome_email', 'Willkommens-E-Mail'), ('promotional', 'Werbung'), ('newsletter', 'Newsletter'), ('birthday_greeting', 'Geburtstagswünsche'), ('follow_up', 'Nachfass-E-Mail'), ('admin_notification', 'Admin Benachrichtigung'), ('custom', 'Benutzerdefiniert')], help_text='Art der E-Mail', max_length=30)),
                ('subject', models.CharField(help_text='E-Mail Betreff (kann Variablen enthalten)', max_length=255)),
                ('html_content', models.TextField(help_text='HTML E-Mail Inhalt')),
                ('text_content', models.TextField(blank=True, help_text='Text E-Mail Inhalt (optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Template aktiv')),
                ('is_default', models.BooleanField(default=False, help_text='Standard-Template für diesen E-Mail-Typ')),
                ('available_variables', models.TextField(blank=True, help_text='Verfügbare Variablen für dieses Template (automatisch generiert)')),
                ('header_image', models.ImageField(blank=True, help_text='Header-Bild für E-Mail', null=True, upload_to='email_templates/')),
                ('footer_text', models.TextField(blank=True, help_text='Footer-Text')),
                ('primary_color', models.CharField(default='#e91e63', help_text='Primärfarbe (Hex)', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Hintergrundfarbe (Hex)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail Template',
                'verbose_name_plural': 'E-Mail Templates',
                'ordering': ['email_type', 'name'],
                'unique_together': {('email_type', 'is_default')},
            },
        ),
    ]
