# Generated by Django 5.2.6 on 2025-09-04 18:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_interval_minutes', models.PositiveIntegerField(default=15, help_text='Zeitintervall zwischen Terminen in Minuten', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('opening_time', models.TimeField(default=datetime.time(9, 0), help_text='Öffnungszeit')),
                ('closing_time', models.TimeField(default=datetime.time(18, 0), help_text='Schließzeit')),
                ('max_concurrent_appointments', models.PositiveIntegerField(default=3, help_text='Maximale Anzahl gleichzeitiger Termine (Anzahl Mitarbeiter)')),
                ('min_advance_booking_hours', models.PositiveIntegerField(default=2, help_text='Mindestvorlaufzeit für Buchungen in Stunden')),
                ('max_advance_booking_days', models.PositiveIntegerField(default=90, help_text='Maximaler Vorlauf für Buchungen in Tagen')),
                ('buffer_time_minutes', models.PositiveIntegerField(default=5, help_text='Pufferzeit zwischen Terminen in Minuten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salon Einstellungen',
                'verbose_name_plural': 'Salon Einstellungen',
            },
        ),
    ]
