# Generated by Django 5.2.6 on 2025-09-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_add_salon_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.CharField(blank=True, help_text="Subcategory like 'Volume 4D-5D', 'Classic 1:1'", max_length=100),
        ),
    ]
