# Generated by Django 5.2.6 on 2025-09-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_service_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='recipient_type',
            field=models.CharField(choices=[('customer', 'An Kunden senden'), ('admin', 'An Admin senden'), ('both', 'An Kunden und Admin senden')], default='customer', help_text='An wen soll die E-Mail gesendet werden', max_length=20),
        ),
    ]
