# Generated by Django 5.2.6 on 2025-09-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_emailtemplate_recipient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time_enabled', models.BooleanField(default=True, help_text='Bật mã giảm giá cho khách mới')),
                ('first_time_percentage', models.DecimalField(decimal_places=2, default=5, help_text='% giảm giá khách mới', max_digits=5)),
                ('first_time_max_amount', models.DecimalField(decimal_places=2, default=20, help_text='Số tiền giảm tối đa khách mới', max_digits=8)),
                ('first_time_min_order', models.DecimalField(decimal_places=2, default=50, help_text='Đơn hàng tối thiểu khách mới', max_digits=8)),
                ('first_time_validity_days', models.PositiveIntegerField(default=30, help_text='Số ngày hiệu lực khách mới')),
                ('birthday_enabled', models.BooleanField(default=True, help_text='Bật mã giảm giá sinh nhật')),
                ('birthday_percentage', models.DecimalField(decimal_places=2, default=5, help_text='% giảm giá sinh nhật', max_digits=5)),
                ('birthday_max_amount', models.DecimalField(decimal_places=2, default=25, help_text='Số tiền giảm tối đa sinh nhật', max_digits=8)),
                ('birthday_min_order', models.DecimalField(decimal_places=2, default=0, help_text='Đơn hàng tối thiểu sinh nhật', max_digits=8)),
                ('birthday_validity_days', models.PositiveIntegerField(default=7, help_text='Số ngày hiệu lực sinh nhật')),
                ('birthday_days_before', models.PositiveIntegerField(default=3, help_text='Gửi mã trước sinh nhật bao nhiêu ngày')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cài đặt mã giảm giá',
                'verbose_name_plural': 'Cài đặt mã giảm giá',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã giảm giá', max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('first_time', 'Đăng ký lần đầu'), ('birthday', 'Sinh nhật'), ('event', 'Sự kiện đặc biệt'), ('vip', 'Khách VIP'), ('referral', 'Giới thiệu bạn bè')], help_text='Loại giảm giá', max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Phần trăm giảm giá', max_digits=5)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền giảm tối đa', max_digits=8, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Giá trị đơn hàng tối thiểu', max_digits=8)),
                ('email', models.EmailField(help_text='Email nhận mã giảm giá', max_length=254)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Số lần đã sử dụng')),
                ('max_usage', models.PositiveIntegerField(default=1, help_text='Số lần sử dụng tối đa')),
                ('valid_from', models.DateTimeField(help_text='Có hiệu lực từ')),
                ('valid_until', models.DateTimeField(help_text='Có hiệu lực đến')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('used', 'Đã sử dụng'), ('expired', 'Đã hết hạn'), ('disabled', 'Vô hiệu hóa')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Khách hàng được cấp mã', null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.customer')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-created_at'],
            },
        ),
    ]
