# Generated by Django 5.2.6 on 2025-09-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_discountsettings_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_format',
            field=models.CharField(choices=[('html', 'HTML'), ('text', 'Plain Text')], default='html', help_text='Content format type', max_length=10),
        ),
    ]
