# Generated by Django 5.2.6 on 2025-09-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_add_content_format_to_blogpost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'completed'])), fields=('staff', 'date', 'time'), name='unique_active_appointment_per_staff_datetime'),
        ),
    ]
